# Generated by Django 4.1.3 on 2022-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employee_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=True),
        ),
    ]
